
-- ============================================================
-- grant_portfolio_analytics | Schema
-- Author: Caroline Nzisa Mwanzia
-- Description: Multi-donor DFI grant portfolio database
-- ============================================================

CREATE DATABASE IF NOT EXISTS grant_portfolio_db;
USE grant_portfolio_db;

-- TABLE 1: PROJECTS (real metadata from World Bank open data)
CREATE TABLE IF NOT EXISTS projects (
    project_id        VARCHAR(20)    PRIMARY KEY,
    project_name      VARCHAR(255)   NOT NULL,
    donor             VARCHAR(100)   NOT NULL,
    country           VARCHAR(100)   NOT NULL,
    sector            VARCHAR(100)   NOT NULL,
    start_date        DATE           NOT NULL,
    end_date          DATE           NOT NULL,
    total_budget_usd  DECIMAL(15,2)  NOT NULL,
    status            VARCHAR(20)    DEFAULT 'Active'
);

-- TABLE 2: EXPENDITURES (simulated monthly transactions)
CREATE TABLE IF NOT EXISTS expenditures (
    expenditure_id      INT            AUTO_INCREMENT PRIMARY KEY,
    project_id          VARCHAR(20)    NOT NULL,
    txn_year            INT            NOT NULL,
    txn_month           INT            NOT NULL,
    category            VARCHAR(50)    NOT NULL,
    -- Categories: Staff, Operations, Procurement, Indirect
    amount_usd          DECIMAL(12,2)  NOT NULL,
    approved_budget_usd DECIMAL(12,2)  NOT NULL,
    FOREIGN KEY (project_id) REFERENCES projects(project_id)
);

-- TABLE 3: DISBURSEMENTS (donor payment schedule vs actuals)
CREATE TABLE IF NOT EXISTS disbursements (
    disbursement_id    INT            AUTO_INCREMENT PRIMARY KEY,
    project_id         VARCHAR(20)    NOT NULL,
    scheduled_date     DATE           NOT NULL,
    actual_date        DATE,
    scheduled_amount   DECIMAL(12,2)  NOT NULL,
    actual_amount      DECIMAL(12,2),
    disbursement_no    INT            NOT NULL,
    -- Tranche number (1st, 2nd, 3rd disbursement etc.)
    FOREIGN KEY (project_id) REFERENCES projects(project_id)
);

-- TABLE 4: FLAGS (risk flags generated by Python engine)
CREATE TABLE IF NOT EXISTS flags (
    flag_id        INT            AUTO_INCREMENT PRIMARY KEY,
    project_id     VARCHAR(20)    NOT NULL,
    flag_type      VARCHAR(50)    NOT NULL,
    -- Types: Slow Disbursement, Budget Overrun Risk,
    --        Covenant Breach, Value-for-Money Alert
    severity       VARCHAR(10)    NOT NULL,
    -- Levels: Low, Medium, High
    flag_date      DATE           NOT NULL,
    notes          TEXT,
    FOREIGN KEY (project_id) REFERENCES projects(project_id)
);
